blank_issues_enabled: false
contact_links:
- name: ðŸ’¬ Bugs
  url: https://gitlab.com/uniget-org/backlog/-/issues/new?type=ISSUE
  about: Something is not working?
- name: âœ¨ Enhancements
  url: https://gitlab.com/uniget-org/backlog/-/issues/new?type=ISSUE
  about: Missing something?
- name: ðŸ“– Documentation
  url: https://docs.uniget.dev
  about: Check for usage and examples
